#!/bin/dash

curr_dir=`pwd`
init_dir="$curr_dir/.shrug"

if test ! -d $init_dir
then
    echo "Initialized empty shrug repository in .shrug"
    mkdir .shrug
    mkdir "$curr_dir/.shrug/index"
    touch "$curr_dir/.shrug/log"
    exit 0
else
    echo "shrug-init: error: .shrug already exists"
    exit 1
fi
    
